// Copyright 2026 SEQSENSE, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package provisioning implements AWS IoT Fleet Provisioning by claim.
//
// It is used by a device connected with a provisioning claim certificate to
// obtain its own certificate and register itself as a thing.
// After provisioning, the claim connection should be closed and a new
// connection should be established using the returned credentials,
// typically with the thing name as the client ID.
//
// Only the JSON payload format is supported.
//
// Response topics of each operation are subscribed on its first call, so the
// policy of the claim certificate only needs to allow the topics of the
// provisioning method in use:
//   - ProvisionWithClaim: $aws/certificates/create/json and
//     $aws/provisioning-templates/<templateName>/provision/json
//   - ProvisionWithCSR: $aws/certificates/create-from-csr/json and
//     $aws/provisioning-templates/<templateName>/provision/json
//
// The Fleet Provisioning MQTT API has no client token to correlate responses
// with requests. Concurrent calls of the same operation are therefore
// serialized. If a call times out, its response may arrive later and be
// received by the next call of the same operation:
//   - CreateKeysAndCertificate returns a key, certificate and token which are
//     consistent with each other, so the late response is usable.
//   - CreateCertificateFromCSR discards responses whose certificate does not
//     match the public key of the signer.
//   - RegisterThing responses cannot be verified.
package provisioning

import (
	"context"
	"crypto"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"sync"

	"github.com/at-wat/mqtt-go"

	"github.com/seqsense/aws-iot-device-sdk-go/v6"
	"github.com/seqsense/aws-iot-device-sdk-go/v6/internal/ioterr"
)

// Provisioning is an interface of IoT Fleet Provisioning.
type Provisioning interface {
	mqtt.Handler
	// OnError sets handler of asynchronous errors.
	OnError(func(error))
	// ProvisionWithClaim creates a private key and certificate by
	// CreateKeysAndCertificate and registers the thing by RegisterThing.
	// The private key is generated by AWS IoT and sent over the claim
	// connection.
	ProvisionWithClaim(ctx context.Context, parameters map[string]string) (*Credentials, error)
	// ProvisionWithCSR creates a certificate of the key of signer by
	// CreateCertificateFromCSR and registers the thing by RegisterThing.
	// The private key never leaves signer, so it can be backed by
	// a hardware security module.
	ProvisionWithCSR(ctx context.Context, signer crypto.Signer, parameters map[string]string) (*Credentials, error)
}

type operation int

const (
	opCreateKeysAndCertificate operation = iota
	opCreateCertificateFromCSR
	opRegisterThing
	numOperations
)

var operations = [numOperations]struct {
	name   string
	topic  func(templateName string) string
	newRes func() interface{}
}{
	opCreateKeysAndCertificate: {
		name:   "CreateKeysAndCertificate",
		topic:  func(string) string { return "$aws/certificates/create/json" },
		newRes: func() interface{} { return &createKeysAndCertificateResponse{} },
	},
	opCreateCertificateFromCSR: {
		name:   "CreateCertificateFromCSR",
		topic:  func(string) string { return "$aws/certificates/create-from-csr/json" },
		newRes: func() interface{} { return &createCertificateFromCSRResponse{} },
	},
	opRegisterThing: {
		name: "RegisterThing",
		topic: func(templateName string) string {
			return "$aws/provisioning-templates/" + templateName + "/provision/json"
		},
		newRes: func() interface{} { return &registerThingResponse{} },
	},
}

func (o operation) String() string {
	return operations[o].name
}

type provisioning struct {
	mqtt.ServeMux
	cli          mqtt.Client
	templateName string
	mu           sync.Mutex
	opMu         [numOperations]sync.Mutex
	subscribed   [numOperations]bool // guarded by opMu
	chResps      map[operation]chan interface{}
	onError      func(err error)
	opts         Options
}

func (p *provisioning) topic(op operation) string {
	return operations[op].topic(p.templateName)
}

// New creates IoT Fleet Provisioning interface.
// templateName is the name of the provisioning template used to register
// the thing.
// Response topics are subscribed on the first call of each operation.
func New(ctx context.Context, cli awsiotdev.Device, templateName string, opts ...Option) (Provisioning, error) {
	p := &provisioning{
		cli:          cli,
		templateName: templateName,
		chResps:      make(map[operation]chan interface{}),
	}
	for _, o := range opts {
		o(&p.opts)
	}

	newErrRes := func() interface{} { return &ErrorResponse{} }
	for op := operation(0); op < numOperations; op++ {
		topic := p.topic(op)
		if err := p.ServeMux.Handle(topic+"/accepted", p.handler(op, operations[op].newRes)); err != nil {
			return nil, ioterr.New(err, "registering message handlers")
		}
		if err := p.ServeMux.Handle(topic+"/rejected", p.handler(op, newErrRes)); err != nil {
			return nil, ioterr.New(err, "registering message handlers")
		}
	}
	return p, nil
}

func (p *provisioning) ProvisionWithClaim(ctx context.Context, parameters map[string]string) (*Credentials, error) {
	cert, err := p.createKeysAndCertificate(ctx)
	if err != nil {
		return nil, err
	}
	pair, err := tls.X509KeyPair([]byte(cert.CertificatePEM), []byte(cert.PrivateKey))
	if err != nil {
		return nil, ioterr.New(err, "loading key pair")
	}
	signer, ok := pair.PrivateKey.(crypto.Signer)
	if !ok {
		return nil, ioterr.New(ErrInvalidResponse, "loading key pair")
	}
	return p.register(ctx, &Credentials{
		CertificateID:  cert.CertificateID,
		CertificatePEM: cert.CertificatePEM,
		PrivateKey:     signer,
	}, cert.CertificateOwnershipToken, parameters)
}

func (p *provisioning) ProvisionWithCSR(ctx context.Context, signer crypto.Signer, parameters map[string]string) (*Credentials, error) {
	pub, ok := signer.Public().(publicKey)
	if !ok {
		return nil, ErrUnsupportedKey
	}
	tmpl := p.opts.CSRTemplate
	if tmpl == nil {
		tmpl = &x509.CertificateRequest{}
	}
	csr, err := x509.CreateCertificateRequest(rand.Reader, tmpl, signer)
	if err != nil {
		return nil, ioterr.New(err, "creating certificate signing request")
	}
	cert, err := p.createCertificateFromCSR(ctx,
		string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE REQUEST", Bytes: csr})),
		pub,
	)
	if err != nil {
		return nil, err
	}
	return p.register(ctx, &Credentials{
		CertificateID:  cert.CertificateID,
		CertificatePEM: cert.CertificatePEM,
		PrivateKey:     signer,
	}, cert.CertificateOwnershipToken, parameters)
}

// register registers the thing and fills the thing information of creds.
func (p *provisioning) register(ctx context.Context, creds *Credentials, token string, parameters map[string]string) (*Credentials, error) {
	thing, err := p.registerThing(ctx, token, parameters)
	if err != nil {
		return nil, err
	}
	creds.ThingName = thing.ThingName
	creds.DeviceConfiguration = thing.DeviceConfiguration
	return creds, nil
}

func (p *provisioning) createKeysAndCertificate(ctx context.Context) (*createKeysAndCertificateResponse, error) {
	// The API expects an empty request; "{}" is sent as AWS IoT Device SDKs do.
	return request[createKeysAndCertificateResponse](ctx, p, opCreateKeysAndCertificate, struct{}{}, nil)
}

// createCertificateFromCSR discards responses whose certificate does not
// have pub as responses to earlier timed-out requests.
func (p *provisioning) createCertificateFromCSR(ctx context.Context, csr string, pub publicKey) (*createCertificateFromCSRResponse, error) {
	return request[createCertificateFromCSRResponse](ctx, p, opCreateCertificateFromCSR,
		&createCertificateFromCSRRequest{CertificateSigningRequest: csr},
		func(res *createCertificateFromCSRResponse) bool {
			return certificateHasPublicKey(res.CertificatePEM, pub)
		},
	)
}

func (p *provisioning) registerThing(ctx context.Context, certificateOwnershipToken string, parameters map[string]string) (*registerThingResponse, error) {
	return request[registerThingResponse](ctx, p, opRegisterThing,
		&registerThingRequest{
			CertificateOwnershipToken: certificateOwnershipToken,
			Parameters:                parameters,
		},
		nil,
	)
}

type publicKey interface {
	Equal(crypto.PublicKey) bool
}

func certificateHasPublicKey(certPEM string, pub publicKey) bool {
	block, _ := pem.Decode([]byte(certPEM))
	if block == nil {
		return false
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return false
	}
	return pub.Equal(cert.PublicKey)
}

// subscribe subscribes response topics of op if not yet subscribed.
// p.opMu[op] must be locked.
func (p *provisioning) subscribe(ctx context.Context, op operation) error {
	if p.subscribed[op] {
		return nil
	}
	topic := p.topic(op)
	if _, err := p.cli.Subscribe(ctx,
		mqtt.Subscription{Topic: topic + "/accepted", QoS: mqtt.QoS1},
		mqtt.Subscription{Topic: topic + "/rejected", QoS: mqtt.QoS1},
	); err != nil {
		return ioterr.Newf(err, "subscribing %s topics", op)
	}
	p.subscribed[op] = true
	return nil
}

// request publishes req and waits for the response of op.
// If match is not nil, accepted responses for which match returns false are
// discarded as responses to earlier timed-out requests.
func request[T any](ctx context.Context, p *provisioning, op operation, req interface{}, match func(*T) bool) (*T, error) {
	p.opMu[op].Lock()
	defer p.opMu[op].Unlock()

	if err := p.subscribe(ctx, op); err != nil {
		return nil, err
	}

	ch := make(chan interface{}, 1)
	p.mu.Lock()
	p.chResps[op] = ch
	p.mu.Unlock()
	defer func() {
		p.mu.Lock()
		delete(p.chResps, op)
		p.mu.Unlock()
	}()

	breq, err := json.Marshal(req)
	if err != nil {
		return nil, ioterr.New(err, "marshaling request")
	}
	if err := p.cli.Publish(ctx,
		&mqtt.Message{
			Topic:   p.topic(op),
			QoS:     mqtt.QoS1,
			Payload: breq,
		},
	); err != nil {
		return nil, ioterr.New(err, "sending request")
	}

	for {
		select {
		case <-ctx.Done():
			return nil, ioterr.Newf(ctx.Err(), "requesting %s", op)
		case res := <-ch:
			switch r := res.(type) {
			case *T:
				if match != nil && !match(r) {
					continue
				}
				return r, nil
			case error:
				return nil, r
			default:
				return nil, ioterr.Newf(ErrInvalidResponse, "requesting %s", op)
			}
		}
	}
}

func (p *provisioning) handler(op operation, newRes func() interface{}) mqtt.HandlerFunc {
	return func(msg *mqtt.Message) {
		res := newRes()
		if err := json.Unmarshal(msg.Payload, res); err != nil {
			// Payload is not included in the error since it may contain a private key.
			p.handleResponse(op, ioterr.Newf(err, "unmarshaling %s response", op))
			return
		}
		p.handleResponse(op, res)
	}
}

func (p *provisioning) handleResponse(op operation, r interface{}) {
	p.mu.Lock()
	ch, ok := p.chResps[op]
	p.mu.Unlock()
	if !ok {
		if err, isErr := r.(error); isErr {
			p.handleError(err)
		}
		return
	}
	select {
	case ch <- r:
	default:
	}
}

func (p *provisioning) OnError(cb func(err error)) {
	p.mu.Lock()
	p.onError = cb
	p.mu.Unlock()
}

func (p *provisioning) handleError(err error) {
	p.mu.Lock()
	cb := p.onError
	p.mu.Unlock()
	if cb != nil {
		cb(err)
	}
}
